spring.application.name=exam_support_dtu
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Nhn28211148885@
spring.jpa.properties.hibernate.default_schema=exam_sp
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ???ng d?n l?u file
file.upload-dir=D:/Tracuulich/exam_support_dtu/uploads/exam_files/

# ( Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=supportdtu@gmail.com
# Mat khau gmail (App Password)
spring.mail.password=cbyn myne qrig ybkd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true