spring.application.name=exam_support_dtu
spring.datasource.url=jdbc:postgresql://localhost:5432/Exam?currentSchema=exam_sp

spring.datasource.username=trung
spring.datasource.password=123456
spring.jpa.properties.hibernate.default_schema=exam_sp
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# l?u tr? file l?ch thi
file.upload-dir=D:/Tracuulich/exam_support_dtu/uploads/exam_files/
# Th? m?c l?u t�i li?u do Sinh vi�n (ho?c Admin) upload l�n
document.upload-dir=D:/Tracuulich/exam_support_dtu/uploads/documents/

# ( Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=supportdtu@gmail.com
# Mat khau gmail (App Password)
spring.mail.password=cbyn myne qrig ybkd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# ==========================================
# C?U H�NH DUNG L??NG UPLOAD FILE
# ==========================================
# Dung l??ng t?i ?a cho M?T file (VD: 50 Megabytes)
spring.servlet.multipart.max-file-size=50MB

# Dung l??ng t?i ?a cho TO�N B? request (D�ng khi up nhi?u file c�ng l�c)
spring.servlet.multipart.max-request-size=500MB

# GEMINI AI CONFIG
gemini.api.key=AIzaSyDq4gaAsdJBOOgxv5C1NVFwN1tCYkUIIFc