spring.application.name=exam_support_dtu
spring.datasource.url=jdbc:postgresql://localhost:5432/Exam
spring.datasource.username=trung
spring.datasource.password=123456
spring.jpa.properties.hibernate.default_schema=exam_sp
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ???ng d?n l?u file
file.upload-dir=D:/Tracuulich/exam_support_dtu/uploads/exam_files/